services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: reebelo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: